Name:           ros-indigo-concert-simple-scheduler
Version:        0.7.0
Release:        0%{?dist}
Summary:        ROS concert_simple_scheduler package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/concert_simple_scheduler
Source0:        %{name}-%{version}.tar.gz

Requires:       PyYAML
Requires:       ros-indigo-concert-msgs
Requires:       ros-indigo-concert-scheduler-requests
Requires:       ros-indigo-rocon-app-manager-msgs
Requires:       ros-indigo-rocon-std-msgs
Requires:       ros-indigo-rospy
Requires:       ros-indigo-scheduler-msgs
Requires:       ros-indigo-unique-id
BuildRequires:  python-catkin_pkg
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-concert-msgs
BuildRequires:  ros-indigo-concert-scheduler-requests
BuildRequires:  ros-indigo-roslint
BuildRequires:  ros-indigo-rospy
BuildRequires:  ros-indigo-rostest
BuildRequires:  ros-indigo-rosunit
BuildRequires:  ros-indigo-scheduler-msgs
BuildRequires:  ros-indigo-unique-id

%description
This ROS package provides a simple, experimental, resource scheduler for the
Robotics in Concert project.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Sun Dec 21 2014 Jack O'Quin <jack.oquin@gmail.com> - 0.7.0-0
- Autogenerated by Bloom

